### PR TITLE
Use Typechain

### LINKED ISSUE #27: Add typechain support
https://www.npmjs.com/package/typechain

### PR DESCRIPTION
**Pull request by rellfy**
Resolves #27

### CODE REVIEW

**Review by Preston-Harrison — APPROVED** [review]

**Comment by rellfy** [comment]
Setting PR as a draft because the github CI isn't cooperating, code should be fine for review still

**Comment by rellfy** [comment]
@ahinchliff pls send help

**Review by OptimusOpus — APPROVED** [review]
LGTM however the tests seems to be failing

**Comment by bitcoinbrisbane** [comment]
> LGTM however the tests seems to be failing

Dont merge unless tests pass :)

**Pull request merged**
